#ifndef LW_ATTRIBUTES
#define LW_ATTRIBUTES

/*
    顶点数据结构
*/
#if SHADERPASS == SHADERPASS_LIGHT_TRANSPORT
    #define ATTRIBUTES_NEED_NORMAL
    #define ATTRIBUTES_NEED_TEXCOORD0
    #define ATTRIBUTES_NEED_TEXCOORD1
    #define ATTRIBUTES_NEED_TEXCOORD2
    #define ATTRIBUTES_NEED_TEXCOORD3

#elif SHADERPASS == SHADERPASS_SHADOWS
    #define ATTRIBUTES_NEED_NORMAL
    #define ATTRIBUTES_NEED_TANGENT

#elif SHADERPASS == SHADERPASS_DEPTH_ONLY
    #define ATTRIBUTES_NEED_NORMAL
    #define ATTRIBUTES_NEED_TANGENT
    #define ATTRIBUTES_NEED_TEXCOORD0

#else
    #define ATTRIBUTES_NEED_NORMAL
    #define ATTRIBUTES_NEED_TANGENT
    #define ATTRIBUTES_NEED_TEXCOORD0
    #define ATTRIBUTES_NEED_TEXCOORD1
#endif
//#define ATTRIBUTES_NEED_COLOR


/*
    变体结构（数据传输结构）
*/
#if SHADERPASS == SHADERPASS_LIGHT_TRANSPORT
    #define VARYINGS_NEED_POSITION_WS
    #define VARYINGS_NEED_POSITIONPREDISPLACEMENT_WS
    #define VARYINGS_NEED_TEXCOORD0
    #define VARYINGS_NEED_TEXCOORD1
    #define VARYINGS_NEED_TEXCOORD2
    #define VARYINGS_NEED_TEXCOORD3

#elif SHADERPASS == SHADERPASS_SHADOWS
    // 不获取任何数据

#elif SHADERPASS == SHADERPASS_DEPTH_ONLY
    #define VARYINGS_NEED_TANGENT_TO_WORLD
    #define VARYINGS_NEED_TEXCOORD0

#else
    #define VARYINGS_NEED_TANGENT_TO_WORLD
    #define VARYINGS_NEED_POSITION_WS
    #define VARYINGS_NEED_TEXCOORD0
    #define VARYINGS_NEED_TEXCOORD1
#endif
//#define VARYINGS_NEED_COLOR
//#define VARYINGS_NEED_CULLFACE

        
/*
    片元数据结构
*/
#if SHADERPASS == SHADERPASS_LIGHT_TRANSPORT
    #if !defined(SHADER_STAGE_RAY_TRACING) && SHADERPASS != SHADERPASS_RAYTRACING_GBUFFER && SHADERPASS != SHADERPASS_FULL_SCREEN_DEBUG
    #define FRAG_INPUTS_ENABLE_STRIPPING
    #endif
    #define FRAG_INPUTS_USE_TEXCOORD0
    #define FRAG_INPUTS_USE_TEXCOORD1
    #define FRAG_INPUTS_USE_TEXCOORD2
    #define FRAG_INPUTS_USE_TEXCOORD3

#elif SHADERPASS == SHADERPASS_SHADOWS
    #if !defined(SHADER_STAGE_RAY_TRACING) && SHADERPASS != SHADERPASS_RAYTRACING_GBUFFER && SHADERPASS != SHADERPASS_FULL_SCREEN_DEBUG
    #define FRAG_INPUTS_ENABLE_STRIPPING
    #endif

#elif SHADERPASS == SHADERPASS_DEPTH_ONLY
    #if !defined(SHADER_STAGE_RAY_TRACING) && SHADERPASS != SHADERPASS_RAYTRACING_GBUFFER && SHADERPASS != SHADERPASS_FULL_SCREEN_DEBUG
    #define FRAG_INPUTS_ENABLE_STRIPPING
    #endif
    #define FRAG_INPUTS_USE_TEXCOORD0

#else
    #if !defined(SHADER_STAGE_RAY_TRACING) && SHADERPASS != SHADERPASS_RAYTRACING_GBUFFER && SHADERPASS != SHADERPASS_FULL_SCREEN_DEBUG
    #define FRAG_INPUTS_ENABLE_STRIPPING
    #endif
    #define FRAG_INPUTS_USE_TEXCOORD0
    #define FRAG_INPUTS_USE_TEXCOORD1
#endif


#endif //着色数据结构宏 | 作者：强辰